/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:866107:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:866107:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:351711:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:351711:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:561466:
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider3:561466:

public void dropList2_click1(GDropList source, GEvent event) { //_CODE_:dropList2:892453:
  println("dropList2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList2:892453:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button3 = new GButton(this, 100, 80, 80, 30);
  button3.setText("Face text");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 10, 80, 80, 30);
  button4.setText("Face text");
  button4.addEventHandler(this, "button4_click1");
  slider3 = new GSlider(this, 10, 130, 170, 40, 10.0);
  slider3.setLimits(0.5, 0.0, 1.0);
  slider3.setNumberFormat(G4P.DECIMAL, 2);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  dropList2 = new GDropList(this, 10, 190, 170, 80, 3, 10);
  dropList2.setItems(loadStrings("list_892453"), 0);
  dropList2.addEventHandler(this, "dropList2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button3; 
GButton button4; 
GSlider slider3; 
GDropList dropList2; 
